### ISSUE TITLE
Event-Driven News Feed with Notifications

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1383]
Summarizing a discussion from stand-up this morning:

- [x] Augment the news feed to more types of events, see #1353
- [x] Make the types of events tracked in the news feed configurable via the profile page
- [ ] Add a "+" button on the home page that allows users to set up different types of news feeds on the home page that each track different types of events 
- [x] Set up user-configurable push, email, text, and in-app notifications on desired news feed events

**Comment by mcoughlin** [comment]
@Theodlz Do you feel like we have fulfilled the spirit of this one? Or is there a separate issue to make that should still be implemented?

**Comment by Theodlz** [comment]
Hi @mcoughlin. `Add a "+" button on the home page that allows users to set up different types of news feeds on the home page that each track different types of events` has not been addresses yet, but I'm not sure we still want that (anything in the newsfeed itself, we added notifications that do the same I believe)?

**Comment by mcoughlin** [comment]
@Theodlz exactly. Want to close it then?

**Comment by Theodlz** [comment]
I think we can yes!
