### ISSUE TITLE
General Frontend Improvements

### ISSUE THREAD

**Issue by kmshin1397** [skyportal/skyportal#1900]
A compilation of various improvements to the UI/UX 

Not including issues related to plots - there are enough of those to have their own Epic

### General
- [x] Replace CSS with CSS-IN-JSX for MUI skyportal#676
- [ ] Make header/navbar narrower skyportal#1749
- [ ] Horizontal scrollbars also want some love skyportal#1708

### Dashboard
- [x] Refresh widgets upon landing on the dashboard skyportal#1891
- [ ] Widget preferences update form improvements skyportal#349
- [ ] Ability to add/remove widgets on the dashboard skyportal#1901
- [x] Add proper minimum sizes and/or scrollbars for resizable widgets skyportal#1902

### Source Page
- [x] Compact comments skyportal#976 / fritz-marshal/fritz-beta-feedback#70
- [x] Comments lists are not responsive to container width skyportal#1613
- [x] Add "?" to low probability classifications skyportal#1393
- [ ] Increase size of classification font on source page fritz-marshal/fritz-beta-feedback#59
- [x] Unify "Submit" Button look and feel on the Source page skyportal#916

### Observability / Observing Runs
- [x] Improve observability tab fritz-marshal/fritz-beta-feedback#61
- [ ] Display observers on observing run page and filter list of observing runs by current date skyportal#1333

### Scanning Page
- [x] Make candidate list end time default to now skyportal#1890

### Groups Page
- [ ] All groups list overflows when there are many groups skyportal#1747
