### ISSUE TITLE
MMA Framework

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#2051]
Epic describing Minimal Viable Product for MMA with skyportal

## General
- [x] Ingest MMA skymaps into database #2049 

## Pages
- [x] List of MMA alerts #2050
- [x] Planning Widget #2054
- [ ] Transient - Source Page #2052

## Modules
- [x] List of plans / requests #2055
- [x] List of observations #2056
- [x] List of galaxies #2058
- [x] List of OTs in localization #2059
- [ ] List of shifts #2061

## API
- [x] Report observations #2057
- [ ] Prepare GCN #2060

## Visualization
- [ ] Skymap Visualization Widget #2053
 
## Filters
- [ ] Implement EM-GW filters #2332

**Comment by mcoughlin** [comment]
![image](https://user-images.githubusercontent.com/2291947/127682093-caa893e9-5175-4a38-a47d-869323977781.png)

How things fits together. And priorities for further development.
