### ISSUE TITLE
2019 EOY goals

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#237]
- [x] Add ability to easily upload source-level thumbnails
- [x] Complete the near finished frontend refactor
- [x] Finalize ingestion from LSST test stream stream
- [x] Security vet the API
- [x] Write up frontend component building docs
- [ ] Convert to TypeScript
- [ ] Complete webhooks
- [x] Deploy example instance on Google cloud
- [x] Determine how to handle spatial indexing

**Comment by stefanv** [comment]
We will probably punt moving to TypeScript at this point.
