### ISSUE TITLE
GRB Triggering Epic

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#3087]
Epic describing triggering ZTF on a GRB

## Notification 
- [x] Notification of GRB ingestion into database #3042

## Front-end
- [x] Interface for the ZTF #3085
- [ ] Improve observation plan interface (#3082, #3081)
- [ ] Automated GCN-like summary #3086
- [x] Default planning interface #3059 

## Back-end
- [ ] Fast source queries #3057
